# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_auto_20170830_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='toBeR_id',
            field=models.IntegerField(null=True),
        ),
    ]
