# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_reservation_tober_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ifJiuZhen',
            field=models.BooleanField(default=False),
        ),
    ]
